swiftboot:
  auth:
    enabled: true
    tokenKey: access_token
    session:
      type: redis
      group: user_session
      expiresIn: 1800
      updateExpireTime: true
      useCookie: true
      cookiePath: /

