spring:
  application:
    name: swiftboot-demo
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/swiftboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 12345678
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/swiftboot
#    username: postgres
#    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      import_files: import.sql
    show-sql: true
    open-in-view: false
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#        jdbc:
#          lob:
#            non_contextual_creation: true
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    org.swiftboot: DEBUG
    org.apache.shiro: DEBUG
shiro:
  enabled: true
  annotations:
    enabled: true
swiftboot:
  data:
    model:
      autoGenerateId: true
      autoUpdateTimeStrategy: on-change
      initData:
        enabled: false
        baseDir: init/
        fallback: true
  auth:
    enabled: false
  shiro:
    enabled: true
    loginUrl: /login
    successUrl: /main
    cookie:
      domain: localhost
      path: /
      name: swiftboot_shiro_token
      maxAge: 300
    session:
      storageType: memory
      timeout: 300
      redisGroup: swiftboot-shiro-session
  demo:
    init:
      users:
        -
          loginName: admin
          loginPwd: 12345678
        -
          loginName: yoda
          loginPwd: 12345678
        -
          loginName: luke
          loginPwd: 12345678
        -
          loginName: dath
          loginPwd: 12345678
      roles:
        -
          name: admin
          desc: Administrator
        -
          name: manager
          desc: Manager
        -
          name: staff
          desc: Staff
        -
          name: guest
          desc: Guest
      permissions:
        -
          code: 'admin'
          desc: '管理员'
          permissions:
            -
              code: 'admin:user'
              desc: '管理员用户'
        -
          code: 'goods'
          desc: '商品'
          permissions:
            -
              code: 'goods:create'
              desc: '创建商品'
            -
              code: 'goods:delete'
              desc: '删除商品'
        -
          code: 'order'
          desc: '订单'
          permissions:
            -
              code: 'order:list'
              desc: '订单列表'
            -
              code: 'order:query'
              desc: '订单查询'
            -
              code: 'order:create'
              desc: '创建订单'
            -
              code: 'order:delete'
              desc: '删除订单'
            -
              code: 'order:save'
              desc: '更新订单'
      rolePermRels:
        admin:
          - '*'
        manager:
          - 'goods:*'
          - 'order:list'
          - 'order:query'
          - 'order:delete'
        staff:
          - 'order:create'
          - 'order:query'
          - 'order:save'
      roleUserRels:
        admin:
          - 'admin'
        manager:
          - 'yoda'
        staff:
          - 'luke'
        guest:
          - 'dath'