swiftboot:
  auth:
    jwt:
      secret: changeme
      # default is 10 minutes
      accessTokenExpirationSeconds: 600
      # default is 24 hours
      refreshTokenExpirationSeconds: 86400
      # `direct` | `refresh` , default is `direct`
      revokeType: refresh
      # `immutable` | `rolling`, default is `immutable`
      refreshMode: rolling
      # `memory` | `redis`, default is `memory`, do not set this if customize your own store implementation.
      storeMode: redis