spring:
  application:
    name: swiftboot-demo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: false
    open-in-view: false
logging:
  file: /var/log/swiftboot-demo.log
  level:
    root: INFO
    org.swiftboot: DEBUG
swiftboot:
  web:
    filter:
      cors: true
    validation:
      resultInJson: false
  data:
    model:
      autoGenerateId: true
      autoUpdateTime: true
      initData: true
      initBaseDir: /Users/allen/Workspace/github/swiftboot/swiftboot-web/src/test/resources/init/
      initBasePackages:
        - org.swiftboot.demo.model.entity
shiro:
  enabled: false
  annotations:
    enabled: false